export enum POPUP {
  STANDARD_DYNAMIC = 'OPEN_POPUP_STANDARD_DYNAMIC',
  CLOSE = 'CLOSE_POPUP',
}

export enum MODAL {
  STANDARD_DYNAMIC = 'OPEN_MODAL_STANDARD_DYNAMIC',
  CLOSE = 'CLOSE_MODAL',
}

export enum VIDEO {
  STANDARD_DYNAMIC = 'OPEN_VIDEO_STANDARD_DYNAMIC',
  CLOSE = 'CLOSE_VIDEO',
}

export enum LIGHTBOX {
  STANDARD_DYNAMIC = 'OPEN_LIGHTBOX_STANDARD_DYNAMIC',
  CLOSE = 'CLOSE_LIGHTBOX',
}
